server:
  port: 8099

downStream:
  url: https://api.openweathermap.org/data/2.5/weather
  apiKey: ZTgxMmYzNjM0NmVhMjkwNzM0NjJmZjFlMDVlMmI0NmI=
  max-days: 7
  max-pagination: 50

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: 6379
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

resilience4j:
  retry:
    instances:
      flightSearch:
        maxRetryAttempts: 3
        waitDuration: 3s
        retryExceptions:
          - java.lang.Exception

splunk:
  username:
  password:
  host:
  port:
  scheme:

